### ISSUE TITLE
replace patterns within files of a particular type

### ISSUE THREAD

**Issue by Dowwie** [TankerHQ/ruplacer#18]
I'd like to replace patterns within files of a particular type, such as "--type rust".  This feature is demonstrated within ripgrep.

**Comment by dmerejkowsky** [comment]
Seems like  the feature is [implemented in ignore](https://docs.rs/ignore/0.4.4/ignore/types/index.html) a crate we already depend on.

So should be easy to implement :)

**Comment by dmerejkowsky** [comment]
Except w

**Comment by dmerejkowsky** [comment]
@Dowwie PR is here :)

Please tell me if you need things like `--type-add` or `--type-clear`. They exist in rg, but I'm not sure we need them in ruplacer too.

**Comment by Dowwie** [comment]
@dmerejkowsky exciting!  will let you know.  thank you for implementing this!

**Comment by dmerejkowsky** [comment]
As soon as #23 is accepted :)

**Comment by dmerejkowsky** [comment]
0.3.0 is out. Enjoy :)

**Comment by Dowwie** [comment]
@dmerejkowsky works! :)  this is a great enhancement.  did you also modify highlighting?

**Comment by dmerejkowsky** [comment]
If you're talking about #15 we may have a solution but it needs more work
