### ISSUE TITLE
Bug with simple replace

### ISSUE THREAD

**Issue by orlov-vo** [TankerHQ/ruplacer#31]
I have some strange behavior with simple replace via windows git bash:
```sh
# ./ruplacer --no-regex --color never -t less  '~styles/' '@/styles/' ./src

Patching ./src\styles\widgets\calendar.less
-- @import '~styles/variables';
++ @import '@C:/Program Files/Git/styles/variables';
```

Version: ruplacer-v0.4.1-windows

**Comment by dmerejkowsky** [comment]
Looks like you've got bitten by msys' automatic path translation.
As a workaround, you can use the MSYS2_ARG_CONV_EXCL environment variable right before running ruplacer, like this:

```bash
$  ruplacer '~styles' '@/styles' ./test --go

Patching ./test\foo.less
-- @import '~styles/variables'
++ @import '@/styles/variables'
```

Some links:

* [Why this happens]http://www.mingw.org/wiki/Posix_path_conversion)
* [How the workaround works](https://github.com/msys2/msys2/wiki/Porting#filesystem-namespaces)

Unfortunately, it seems there is no way to fix this inside ruplacer code.

Hope this helps!
