### ISSUE TITLE
subvert does not replace all lower/upper case matches

### ISSUE THREAD

**Issue by blastrock** [TankerHQ/ruplacer#32]
Steps to reproduce:

```
echo 'stuffStuff stuffstuff STUFFSTUFF' > f
ruplacer stuffStuff fooFoo --subvert
```

Obtained result: only the first "stuffStuff" is replaced
Expected result: all three should be replaced

**Comment by CoolOppo** [comment]
Can confirm:
![image](https://user-images.githubusercontent.com/1498177/58061433-16155480-7b44-11e9-9902-e97385b836bb.png)

**Comment by dmerejkowsky** [comment]
So I have good news and bad news.

The good news is that I made a pull request that solves the issue: #34 

The bad news is that merging #34 would introduce a change in behavior.

Before:
```
ruplacer --subvert foo_bar SpamEggs
- foo_bar, FooBar, FOO_BAR and foo-bar
+ spam_eggs, SpamEggs, SPAM_EGGS and spam-eggs
```

after:

```
ruplacer --subvert foo_bar SpamEggs
- foo_bar, FooBar, FOO_BAR and foo-bar
+ spam_eggs, SpamEggs, SPAMEGGS and spam-eggs
```

My instinct tells me to apply the motto "in case of ambiguity, resist the temptation to guess" and just 
return an error if the pattern and the replacement are inconsistent when building the subvert query.

Thoughts?

**Comment by CoolOppo** [comment]
Did you accidentally switch the before and after? It looks to me like the "before" is completely correct.

**Comment by dmerejkowsky** [comment]
Not sure I'm clear enough, then :) 

But you can look at the [test failures](https://travis-ci.org/TankerHQ/ruplacer/jobs/535200593#L657) to see what I mean

**Comment by dmerejkowsky** [comment]
Won't fix. See #34  for details.
