### ISSUE TITLE
--no-regex should be -F or --fixed-strings

### ISSUE THREAD

**Issue by blastrock** [TankerHQ/ruplacer#33]
Most other tools use these argument names. For example, grep:

    -F, --fixed-strings       PATTERNS are strings

Or rg:

      -F, --fixed-strings                     
            Treat the pattern as a literal string instead of a regular expression. When
            this flag is used, special regular expression meta characters such as .(){}*+
            do not need to be escaped.

**Comment by dmerejkowsky** [comment]
Yeah but I never liked the `--fixed-strings` option. Deal with it
