### ISSUE TITLE
Implement file renaming

### ISSUE THREAD

**Issue by dmerejkowsky** [TankerHQ/ruplacer#9]
```
ruplacer old new --go --rename-files

src/old.py -> src/new.py
```

**Comment by dmerejkowsky** [comment]
Note: might be a bit risky and outside the scope of ruplacer, especially if subdirectories are involved.

Tools like [vidir](https://linux.die.net/man/1/vidir) might be better suited for this task

**Comment by CoolOppo** [comment]
Please do this, it would be awesome.

**Comment by dmerejkowsky** [comment]
I'm now pretty sure it's a dangerous idea. ranger / vidir / bulk are more suited to the task.

**Comment by alxpettit** [comment]
Why is it intrinsically dangerous?
